### ISSUE TITLE
The position of Layer Norm in Patch Embedding Layer

### ISSUE THREAD

**Issue by SY-Xuan** [aanna0701/SPT_LSA_ViT#3]
Interesting Work! I have some questions about some implementation details.
In the original ViT or Swin, the Layer Norm in Patch Embedding Layer is added after the Linear Projection. In your proposed SPT, you add the Layer Norm before the Linear Projection. Have you ever done some ablation about the position of the Layer Norm in Patch Embedding Layer? Why do you put it before the Linear Projection?

**Comment by aanna0701** [comment]
As you said, the normalization position in the patch embedding layer is different.
The patch merging layer used as the pooling layer in Swin has a pre-normalization structure, and we followed this structure.
This part is not a big difference in terms of architecture, but it seems to have some effect on performance.
As a result of our confirmation, when ViT and Swin are tested in CIFAR100, the performance loss is about 0.5% when normalization comes after the linear layer.
So we propose a pre-normalization structure.

**Comment by SY-Xuan** [comment]
Thanks for your kindly reply. Good work. Hope you have a nice day.
